### PR TITLE
updated version number to 5.5.2 Tanks to MihkelBaranov 

### PR DESCRIPTION
**Pull request by luxcium**
I have resubmitted the changes that  **[MihkelBaranov](/MihkelBaranov)**  wants to merge here [Remove lodash dependency](#104) in a new pull request: [Feature/remove lodash dependency](#252)

### CODE REVIEW

**Comment by luxcium** [comment]
capture d ecran le 2019-02-27 a 23 38 35
also updated coveralls to reset the cached image from 87% to 91%

**Comment by luxcium** [comment]
**@szokodiakos**, **@Ben305** and other working on this project...  Just a quick message to let you know I installed and configured **TSLint** + **Prettier** and **EditorConfig**. I use [VS Code](https://code.visualstudio.com/)  with [**Prettier - Code formatter**](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) by **@esbenp** [(Esben Petersen)](https://github.com/prettier/prettier-vscode)  and with [**integrated TSLint**](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) by [Microsoft](https://github.com/Microsoft/vscode-typescript-tslint-plugin) (along with [**EditorConfig for VS Code**)](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) by @jedmao, @chrisdias, @SamVerschueren, @alexandrudima and by @EditorConfig team ... I updated `.vscode/settings.json` and `.editorconfig` accordingly to work with `.prettierrc` and `tslint.json` files to auto fix errors in VS Code. Let me know what you think of the new work flow ...

**Comment by Ben305** [comment]
@luxcium Please keep pull requests clean, don‘t mix multiple things. If this is a PR that increases the Version number, it should only contain those changes. Please also rebase on master. 

I‘d like to keep the commit history clean and straight forward b

**Comment by luxcium** [comment]
> @luxcium Please keep pull requests clean, don‘t mix multiple things. If this is a PR that increases the Version number, it should only contain those changes. Please also rebase on master.
> 
> I‘d like to keep the commit history clean and straight forward b

the previously committed changes are here twice how should I remove them ? 
can you approuve this merge regardless or do I have to change something ?

**Comment by luxcium** [comment]
[@Ben305](/Ben305 ) also if those changes are accepted it include the pull request #74 by 
[@Omegahorus](/Omegahorus) to: [make all properties writable in class](#74)  if you accept mine you should remove the other

**Comment by luxcium** [comment]
@Ben305 I am trying to separate the stuff and will resubmit a new pull request

**Pull request closed without merging**
