### PR TITLE
Allow refType to be defined in @prop (issue #146)

### PR DESCRIPTION
**Pull request by mattjennings**
Improving on #148, I restricted the PropOptions.refType to be a union type of strings 'number', 'string', 'Buffer', and 'ObjectID'.

I previously was doing a union type of 

```js
mongoose.Schema.Types.Number | 
mongoose.Schema.Types.String | 
mongoose.Schema.Types.ObjectID | 
mongoose.Schema.Types.Buffer
```

however when mongoose.Schema.Types.Buffer is part of the union type then Typescript seemed to allow any of the mongoose.Schema.Types

Ref has also been modified a bit to cast the correct refType.

A prop example of how it can be used:

```ts
  @prop({ ref: Car, refType: 'number' })
  car?: Ref<Car, number>;
```

### CODE REVIEW

**Comment by mattjennings** [comment]
As an additional note, I was really hoping to figure out a way to just define the refType by doing

```ts
  @prop({ ref: Car })
  car?: Ref<Car, number>;
```

but I'm not familiar enough with reflect-metadata to know what the process might be. I ran into https://github.com/Microsoft/TypeScript/issues/9916 which suggests this might not be possible.

**Comment by nihiluis** [comment]
any news?

**Comment by hasezoey** [comment]
@mattjennings, when you still work with typegoose / willing todo so, would you resolve the merge conflicts, and try to get news on this?

---

could someone say to me why someone would do `Ref<Car, number>` (2 things, not just `Ref<Car>`)? i dont understand it currently...

**Comment by mattjennings** [comment]
Sorry, I haven't used typegoose in over a year (since making the PR), so I'm afraid I'm not familiar enough anymore to address the conflicts.

@hasezoey I think you're right that it meant `Ref<Class, Type>`, but again, it's been so long I can't really remember.

**Comment by mfulop** [comment]
Hi!

Merged, solved conflicts and added tests here (also added itemsRefType):

https://github.com/mfulop/typegoose

Should I post a separate pull request from that repo?

**Comment by hasezoey** [comment]
@mfulop yes, please open a new pr if you have a diffrent repo than here
-> i looked at your repo, please rebase onto master, then i will review your pr

**Comment by mfulop** [comment]
Sure, will do. AFK for a hour or two

**Comment by mfulop** [comment]
I think I did :) please see #369

**Comment by hasezoey** [comment]
@mfulop you dont need to mention it, i am subscribed to the whole project :)

**Comment by mfulop** [comment]
I know I am just not sure the rebase went well

**Comment by hasezoey** [comment]
this can be closed in favor of #369, because it includes tests and is on a newer master

@Ben305

**Pull request closed without merging**
