### PR TITLE
Add support for multiple collection names

### PR DESCRIPTION
**Pull request by dfletch15**
Check if model has a provided collection name and save the model with collection name appended.  This allows multiple models with different collection names to be built from the same class.

### CODE REVIEW

**Comment by hasezoey** [comment]
Could you give a code sample how to use it?

**Comment by dfletch15** [comment]
Here is a sample controller and model making use of my Typegoose feature.

[sample_code.zip](https://github.com/szokodiakos/typegoose/files/3221983/sample_code.zip)

**Comment by hasezoey** [comment]
Found your solution (as a workaround) [i made the dummy code a bit smaller, with everything to run it)

```ts
import * as mongoose from "mongoose";
import { prop, Typegoose } from "typegoose";

export class Person extends Typegoose {
    @prop()
    public name?: string;
}

function modelGen(type: string) {
    return mongoose.model("Person" + type, new Person().getModelForClass(Person).schema, type);
}

(async () => {
    mongoose.set("debug", true);
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify282",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const model1 = modelGen("model1");
    const model2 = modelGen("model2");
    await new model1({ name: "hello Model1" }).save();
    await new model2({ name: "hello Model2" }).save();
    await new model1({ name: "hello Model1 #2" }).save();

    await mongoose.disconnect();
})();

```

**Comment by hasezoey** [comment]
Yes could verify that its working ~~after tsc & npm would let me, had problems both wouldnt accept git typegoose~~
-> and yes its easier than the workaround

```ts
import * as mongoose from "mongoose";
import { prop, Typegoose } from "./typegoose/src/typegoose"; // note had to install typegoose as source

export class Person extends Typegoose {
    @prop()
    public name?: string;
}

function modelGen(type: string) {
    return new Person().getModelForClass(Person, {
        schemaOptions: {
            collection: type
        }
    });
}

(async () => {
    await mongoose.connect(`mongodb://mongodb:27017/`, {
        useNewUrlParser: true,
        useFindAndModify: true,
        useCreateIndex: true,
        dbName: "verify282",
        user: "user",
        pass: "passwd",
        authSource: "admin",
        autoIndex: true
    });

    const model1 = modelGen("model1");
    const model2 = modelGen("model2");

    await new model1({ name: "hello Model1" }).save();
    await new model2({ name: "hello Model2" }).save();
    await new model1({ name: "hello Model1 #2" }).save();

    await mongoose.disconnect();
})();
```

PS: test's would be good

**Comment by dfletch15** [comment]
Thank you for testing it out!  The mongoose.model() workaround does work but requires the dev to interface with mongoose rather than strictly use Typegoose which I believe is better.
P.S. I'm kinda new to this so I appreciate your feedback.

**Comment by Christilut** [comment]
I used this to achieve multiple collections with the same schema (based on the earlier code):

```ts
export function generateModel<T>(model: mongoose.Model<InstanceType<T>>, name: string): mongoose.Model<InstanceType<T>> {
  return mongoose.model(name, model.schema, name) as mongoose.Model<InstanceType<T>>
}
```

```ts
const model = new Song().getModelForClass(Song, {
  schemaOptions: {
    timestamps: true
  }
})

export const SongModel = generateModel<Song>(model, 'songs')
export const AnotherSongModel = generateModel<Song>(model, 'more_songs')
```

**Comment by hasezoey** [comment]
Custom version of this is included in v6 
docs: hasezoey.github.io/typegoose/guides/advanced/models-with-same-name/
commit: f73cca004682e85a63896353c9dcfc1311c2b464

**Comment by hasezoey** [comment]
@Ben305 Bump for close

**Pull request closed without merging**
