### PR TITLE
Adding Maintainer notes

### PR DESCRIPTION
**Pull request by hasezoey**
- modify CONTRIBUTING to include how to structure commits
- modify package.json Versions to include majors, where it should be included
- modify README to include how this package is Versioned
- adding "Notes to Maintainers" to know how the processes work

@Ben305 i would need to know which version of the merge method is / should / will be used and to confirm that the versioning is correct

### CODE REVIEW

**Comment by hasezoey** [comment]
Note: i dont know why coveralls reports that there is a -0.8%, when not even modifying the code

**Comment by Ben305** [comment]
@hasezoey I prefer squash and merge to keep the history clean.

**Comment by hasezoey** [comment]
@Ben305, i would prefer if it would be "ff", but only if the commits are correctly structured :)
and #359, i "couldnt" use ff or squash, because i wanted that all the issues & prs are "preserved" and closed (and showed as merged and not closed)

**Comment by hasezoey** [comment]
@Ben305 is that acceptable now? (if you dont know what "ff" does compared to "no-ff": "no-ff" adds always an merge commit, and "ff" does never add a merge commit and tries to just put the commits into the timeline without modifying them, so i added an case for that) :)

**Comment by hasezoey** [comment]
@Ben305 2 questions for you:
- i noticed you still have the branch `release-5.7.2` in this repo, is this still needed?
- and i noticed that you make a new branch (example "v5.9.0", or is this a tag?), because the travis deploy is never run because of that ...

**Comment by hasezoey** [comment]
@Ben305 would this be right if i let it so as the final version? (use Fast-Forward, when possible and fits the style?)

**Pull request merged**
