### PR TITLE
Add the possibility to use instance methods in sub schemas

### PR DESCRIPTION
**Pull request by cjanietz**
This pull request adds the ability to also use methods in sub schemas.

### CODE REVIEW

**Comment by talbronfer** [comment]
@szokodiakos can we approve this PR? I also ran into a similar problem as described in #209. Would be helpful if we could get support for instance methods on sub schemas.

**Comment by alex-deas** [comment]
@szokodiakos Any progress on this? Working around this issue leads to a lot of duplicated logic for us

**Comment by jkanczler** [comment]
It would be good to be merged and released.

**Comment by JulianMelzig** [comment]
> @szokodiakos Any progress on this? Working around this issue leads to a lot of duplicated logic for us

Do you have an example for a workaround ?

**Comment by alex-deas** [comment]
@JulianMelzig Not the exact implementation as we now just host the updates in an internal package but it consisted of just putting the putting the logic as a top level instance method. Not ideal as our use case was used across multiple classes.

Unless anyone else want to maintain a fork, I'm happy to publish my fork which contains these changes. I've reimplemented the changes there but if @cjanietz want to PR the original changes I can do a reset on the commit and accept their commit instead.

A couple of other changes I'm currently in the process of implementing is an improvement to that default subclasses are instantiated, although this is unlikely to be completed for a little while yet

**Comment by jkanczler** [comment]
In version 5.6.0, it's not working for me. :-/

```
export class Book extends Typegoose {
    public id?: string;

    @prop({ required: true })
    public name: string;

    @prop({ required: true })
    public defaultCurrency: Currency;

    @instanceMethod
    public async addAccount(this: Book, accountToAdd: Account) {
```

console.log:
```
[1] application is listening on port '8000'.
[1] { _id: ,
[1]   name: '',
[1]   defaultCurrency:
[1]    { _id: 5c7e82b871fc3b316c916369,
[1]      code: '',
[1]      name: '',
[1]      format:
[1]       { _id: ,
[1]         prefix: '',
[1]         thousandSeparator: ' ',
[1]         decimalSeparator: ',',
[1]         suffix: '' } } }
```

**Comment by jkanczler** [comment]
Okay, it's not working if the sub schema is an array. :-/

**Pull request merged**
