### PR TITLE
Add missing "get" and "set" property options

### PR DESCRIPTION
**Pull request by neilime**
As describe in mongoose doc, we can define "get" and "set" options to be used as property getter and setter : https://mongoosejs.com/docs/api.html#schematype_SchemaType-set

### CODE REVIEW

**Comment by Ben305** [comment]
@neilime Would you mind adding some tests?

**Comment by anirbanagp** [comment]
It is still not available in downloaded package. can you please check?

**Comment by neilime** [comment]
@Ben305, sorry for the delay, I have added some tests

**Comment by hasezoey** [comment]
how is this pr different from the virtual properties? 
because these are already mongoose get- & set- -ters

-> is this still a problem in the latest master?

**Comment by hasezoey** [comment]
this can be closed in favor of a123c490297197fda77e1adedc39205da5e821ba and d357d373ba515cdd37649aabd355c0b9c084de7b

@Ben305

**Pull request closed without merging**
