### PR TITLE
use-static-MODEL_NAME-for-constructor.name-alternative

### PR DESCRIPTION
**Pull request by devdoomari3**
why: I'm having trouble with webpack production mode's name-mangling.
Specifically, even when I create:

```
class User extends Typegoose {
  ... 
}
```

the 'User' class often is not 'User' after name-mangling.

This is problematic when I use ```webpact --production```.

ps: a better solution would be to add a 'preserve-name-for-next-line-comment' feature on uglifyjs, but I'm still waiting for that to happen)

### CODE REVIEW

**Comment by hasezoey** [comment]
@devdoomari3, if you still use typegoose, or want to help, could you rebase / edit your pr to be working with the lastest master or close it?

---

> ps: a better solution would be to add a 'preserve-name-for-next-line-comment' feature on uglifyjs, but I'm still waiting for that to happen)

does `uglifyjs` still dosnt have this feature?
Note: i dont know webpack or uglifyjs

**Comment by hasezoey** [comment]
@Ben305 should this be made as a "wontfix"?
its not mainly typegoose's fault for this, and it should (by design) use the class name

**Comment by devdoomari3** [comment]
@hasezoey sorry for the late reply...

I also think typegoose isn't the right place to insert this 'fix'
(the correct fix would be adding options to preserve class names in uglify / terse js)
you can discard this PR.

ps. 
https://github.com/mishoo/UglifyJS2/issues/3263 : didn't work out...

https://github.com/terser-js/terser
has options regarding 'mangle' -> 'preserve', but I really hope they would implement comment-based options.

**Comment by hasezoey** [comment]
@devdoomari3 if its not an issue with typegoose / anymore, could you close this?

**Pull request closed without merging**
