### PR TITLE
Use `existingMongoose` in `buildSchema`

### PR DESCRIPTION
**Pull request by floriansimon1**
Not doing it makes my project with Mongoose v5 crash. The fix can be useful to anybody
that doesn't use Typegoose's mongoose version

### CODE REVIEW

**Comment by floriansimon1** [comment]
This makes Typegoose usable in the frontend without importing Mongoose at all.

**Comment by HarelAshwal** [comment]
LK"I

Hi There,
Can you give example on how to your typegoose Models with the frontend??

**Comment by floriansimon1** [comment]
You can't. The only thing you can do is share the type with the frontend

**Comment by hasezoey** [comment]
Can you give an example how/why this pull request should be used?

PS: and fix the merge conflicts?

**Comment by floriansimon1** [comment]
Unfortunately, I don't have the time for that. It's been a while since I last touched the code base.

**Comment by HarelAshwal** [comment]
LK"I

too bad, had to do this myself.. :)
i've tweaked the code to support both server/client!

[typegoose-frontend](https://www.npmjs.com/package/typegoose-frontend)
hopefully someone can create a pull request and integrate this to typegoose

**Pull request closed without merging**
