### PR TITLE
Feature/remove lodash depedency

### PR DESCRIPTION
**Pull request by luxcium**
```
11 passing (2s)

--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------|----------|----------|----------|----------|-------------------|
All files           |    93.66 |    81.13 |    91.04 |    93.31 |                   |
 src                |    90.22 |    81.82 |    89.19 |    89.71 |                   |
  data.ts           |      100 |      100 |      100 |      100 |                   |
  errors.ts         |       50 |      100 |        0 |       50 |         3,9,15,21 |
  hooks.ts          |      100 |      100 |      100 |      100 |                   |
  index.ts          |      100 |      100 |      100 |      100 |                   |
  method.ts         |    91.67 |      100 |      100 |    91.67 |                 7 |
  plugin.ts         |      100 |      100 |      100 |      100 |                   |
  prop.ts           |    86.15 |    95.65 |      100 |    85.25 |... 42,147,153,216 |
  typegoose.ts      |    95.83 |    64.71 |      100 |    95.74 |             51,53 |
  utils.ts          |     91.3 |       50 |      100 |       90 |             19,37 |
 src/test/enums     |      100 |      100 |      100 |      100 |                   |
  genders.ts        |      100 |      100 |      100 |      100 |                   |
  role.ts           |      100 |      100 |      100 |      100 |                   |
 src/test/hookTests |      100 |      100 |      100 |      100 |                   |
  dummy.ts          |      100 |      100 |      100 |      100 |                   |
  hooktestModel.ts  |      100 |      100 |      100 |      100 |                   |
 src/test/models    |     97.2 |    66.67 |     87.5 |    97.06 |                   |
  car.ts            |      100 |      100 |      100 |      100 |                   |
  job.ts            |      100 |      100 |      100 |      100 |                   |
  nested-object.ts  |      100 |      100 |      100 |      100 |                   |
  person.ts         |    86.96 |      100 |    66.67 |    86.36 |          22,28,35 |
  rating.ts         |      100 |      100 |      100 |      100 |                   |
  user.ts           |      100 |    66.67 |      100 |      100 |                88 |
 src/test/utils     |      100 |       75 |      100 |      100 |                   |
  mongoConnect.ts   |      100 |       75 |      100 |      100 |                10 |
--------------------|----------|----------|----------|----------|-------------------|
```

### CODE REVIEW

**Comment by luxcium** [comment]
// faild validation will need to be checked
  it('Should validate Decimal128', async () => {
    try {
      await Car.create({
        model: 'Tesla',
        price: 'NO DECIMAL',
      });
      fail('Validation must fail.');
    } catch (e) {
      expect(e).to.be.a.instanceof((mongoose.Error as any).ValidationError);
    }
    const car = await Car.create({
      model: 'Tesla',
      price: mongoose.Types.Decimal128.fromString('123.45'),
    });
    const foundCar = await Car.findById(car._id).exec();
    expect(foundCar.price).to.be.a.instanceof(mongoose.Types.Decimal128);
    expect(foundCar.price.toString()).to.eq('123.45');
  });

**Comment by luxcium** [comment]
I resubmitted the changes from : Remove lodash dependency #104
**[MihkelBaranov](/MihkelBaranov) ** commented [on 28 Feb 2018](#issue-171907178)

**Comment by luxcium** [comment]
```

  12 passing (2s)

---------------------|----------|----------|----------|----------|-------------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------|----------|----------|----------|----------|-------------------|
All files            |    95.73 |    73.13 |    92.21 |    94.88 |                   |
 src                 |    93.58 |    69.64 |    90.48 |    92.39 |                   |
  data.ts            |      100 |      100 |      100 |      100 |                   |
  errors.ts          |      100 |        0 |       50 |      100 |        5,11,17,23 |
  hooks.ts           |      100 |      100 |      100 |      100 |                   |
  index.ts           |      100 |      100 |      100 |      100 |                   |
  method.ts          |    91.67 |      100 |      100 |    91.67 |                 9 |
  plugin.ts          |      100 |      100 |      100 |      100 |                   |
  prop.ts            |    86.76 |       96 |      100 |       85 |... 46,151,157,220 |
  typegoose.ts       |     97.1 |    63.16 |      100 |     96.3 |             57,59 |
  utils.ts           |     91.3 |       50 |      100 |    90.48 |             21,39 |
 src/test/enums      |      100 |      100 |      100 |      100 |                   |
  genders.ts         |      100 |      100 |      100 |      100 |                   |
  role.ts            |      100 |      100 |      100 |      100 |                   |
 src/test/hookTests  |      100 |      100 |      100 |      100 |                   |
  dummy.ts           |      100 |      100 |      100 |      100 |                   |
  hooktestModel.ts   |      100 |      100 |      100 |      100 |                   |
 src/test/models     |    97.83 |    85.71 |    91.67 |    97.35 |                   |
  PersistentModel.ts |    82.35 |      100 |       50 |    78.57 |          14,20,27 |
  car.ts             |      100 |      100 |      100 |      100 |                   |
  job.ts             |      100 |      100 |      100 |      100 |                   |
  nested-object.ts   |      100 |      100 |      100 |      100 |                   |
  person.ts          |      100 |      100 |      100 |      100 |                   |
  rating.ts          |      100 |      100 |      100 |      100 |                   |
  user.ts            |      100 |       75 |      100 |      100 |                88 |
 src/test/utils      |      100 |      100 |      100 |      100 |                   |
  mongoConnect.ts    |      100 |      100 |      100 |      100 |                   |
---------------------|----------|----------|----------|----------|-------------------|
```

**Comment by luxcium** [comment]
> [Coverage Status](https://coveralls.io/builds/21847493)
> 
> Coverage increased (+4.3%) to 91.228% when pulling **[431aa10](https://github.com/szokodiakos/typegoose/commit/431aa107df30e8d0c4cec9f34b22d32dc7a5b9d9) on luxcium:feature/removeLodashDepedency** into **[56a2e7d](https://github.com/szokodiakos/typegoose/commit/56a2e7d94ecf81b2d1099fdd3be52166e1431d1f) on szokodiakos:master**.

@szokodiakos can you review my changes and tell me if they can be approuved ?

**Comment by Ben305** [comment]
@luxcium Great, thank you!

**Pull request merged**
