### PR TITLE
 guard against undefined schema definitions in buildSchema

### PR DESCRIPTION
**Pull request by iyiolapeter**
Currently, there is no check if the parent class has a valid schema which causes mongoose to complain since argument passed to schema.add will now be undefined.

### CODE REVIEW

**Comment by hasezoey** [comment]
this can be closed, because mongoose accepts undefined (`new Schema(undefined)`)

**Comment by iyiolapeter** [comment]
> this can be closed, because mongoose accepts undefined (`new Schema(undefined)`)
> 
> @Ben305

While you can pass undefined during instantiation, this does not work with Schema.prototype.add which is referenced in buildSchema.

sch.add(undefined) fails with 'Cannot read property '_id' of undefined\n    at Schema.add'

**Comment by hasezoey** [comment]
> which is referenced in buildSchema

in the latest changed, buildSchema dosnt have "sch.add" anymore, it is outsourced to "_buildSchema" which creates an schema first, and only after that calls an "sch.add"

**Comment by hasezoey** [comment]
reference:
https://github.com/szokodiakos/typegoose/blob/0d68100051cef0e9ec2ff1346a574e0873f1873e/src/typegoose.ts#L124-L132
(logic in words: "if not 'sch' create one")

**Comment by hasezoey** [comment]
after working on https://github.com/hasezoey/typegoose/issues/9 i noticed that i now know the point of this pr (sorry), a better(refactored) version will be included in 6.0.0

**Comment by hasezoey** [comment]
This can be closed, in favor of v6.0.0 (it is "included")

Note:
in v6.0.0 it cannot happen, because:
(context: speaking of `_buildSchema`)
- if `sch` is not an instance of `mongoose.Schema` it creates a new one
- adds a test for it

fffbea2ff5ebefa2e1627481bc8e1491824795e7

@Ben305 This can be closed

**Pull request closed without merging**
