### PR TITLE
Add missing string validation options

### PR DESCRIPTION
**Pull request by Y0hy0h**
The current types do not support all [string validation options](http://mongoosejs.com/docs/schematypes.html#schematypes).

Missing:
- lowercase
- uppercase
- trim
- enum

I hope I didn't miss anything, since it was very easy to add these to the `ValidateStringOptions` type.

### CODE REVIEW

**Comment by Ben305** [comment]
@Y0hy0h This looks already pretty good, but I cannot get the validation to work. Can you add some tests to show that the implementation is working as expected?

**Comment by Y0hy0h** [comment]
Unfortunately, I could not make the tests run on my machine. Somehow the beforeAll hook and all tests timed out.

I created some tests nevertheless. Maybe I'm lucky and they run on CI. :D At the very least they should provide a starting point.

**Comment by Y0hy0h** [comment]
So the tests for the transformative validators seem to pass. However, the protective validators [do not throw a `mongoose.Error`](https://travis-ci.org/szokodiakos/typegoose/jobs/381042827#L718), like I anticipated. What is the correct behavior, when I try to save an object that violates a validator?

**Comment by Ben305** [comment]
@Y0hy0h The problem is that this test does not throw any error. Really strange...

**Comment by hasezoey** [comment]
fixed the tests:
1. in model it was named "maxLength" in tests was called "maxlength" (the "L")
2. in model it was named "enumed" in tests was called "enum" (the "ed")
3. if both would be fixed, they would error out because "Promise Rejection", my fix was using "chai-as-promised"

like so
```ts
describe('string validators', () => {
    // TODO: Specify an identifier for the error messages, e. g. as a regex to the message content.
    // Otherwise we could catch errors that have nothing to do with what is being tested.

    it('should respect maxlength', (done) => {
      expect(StringValidators.create({
        maxLength: 'this is too long',
      })).to.eventually.rejectedWith(mongoose.Error).and.notify(done);
    });

    it('should trim', async () => {
      const trimmed = await StringValidators.create({
        trimmed: 'trim my end    ',
      });
      expect(trimmed.trimmed).equals('trim my end');
    });

    it('should uppercase', async () => {
      const uppercased = await StringValidators.create({
        uppercased: 'make me uppercase',
      });
      expect(uppercased.uppercased).equals('MAKE ME UPPERCASE');
    });

    it('should respect enum', (done) => {
      expect(StringValidators.create({
        enumed: 'i am not valid',
      })).to.eventually.rejectedWith(mongoose.Error).and.notify(done);
    });
  });
```

and at the top of the file
```ts
import { expect, use } from 'chai';
import * as cap from "chai-as-promised";
use(cap);
```

PS: fix the merge conflicts, thanks

**Comment by Y0hy0h** [comment]
I no longer use typegoose, so I would like to transfer responsibility of this PR. Can someone take over?

**Comment by hasezoey** [comment]
i could take over

**Comment by Y0hy0h** [comment]
Don you want to fork my code and create a new PR? Or is there another option?

**Comment by hasezoey** [comment]
> Don you want to fork my code and create a new PR? Or is there another option?

made already with #293

**Comment by Y0hy0h** [comment]
Closed in favor of #293.

Thanks, @hasezoey!

**Pull request closed without merging**
