### PR TITLE
Updated 'ref' parameter to allow population by string

### PR DESCRIPTION
**Pull request by ChristianPraiss**
This can be useful when working with a mixed ts/js project

### CODE REVIEW

**Comment by devdoomari3** [comment]
@ChristianPraiss your commit has some minor lint errors:

https://travis-ci.org/szokodiakos/typegoose/jobs/380603087#L684

btw, I'd love to see your PR merged into typegoose! 
I'm working on a JS->TS transition (with mongoose), and the current limit forces me to start with only a handful of non-dependent models...

ps: I'm wondering if @szokodiakos  or any other admins for the repo can merge the PRs...

**Comment by Ben305** [comment]
I‘ll merge this when the tests are working again.

**Comment by ChristianPraiss** [comment]
So i fixed the linter errors, but 1 of 2 test runs on travis-ci failed, though this doesn't seem to be caused by the changes i made, a Decimal type validation seems to fail. Could someone check what goes wrong there? @Ben305 @devdoomari3

**Comment by Ben305** [comment]
@ChristianPraiss I've fixed the problems in `master`, so you should rebase your branch and all checks should be executed successfully again.

**Comment by ChristianPraiss** [comment]
There we go 👍

**Comment by Ben305** [comment]
Released as v5.3.0

**Pull request merged**
