### PR TITLE
Schema inheritance

### PR DESCRIPTION
**Pull request by ukoester**
Extension of the method 'getModelForClass' of the class 'Typegoose' to achieve inheritance of the schema. Unit tests (and models) have been added. Can you please check my fork and if you have comments please let me know. I would be very happy if you would merge my fork.

### CODE REVIEW

**Comment by szokodiakos** [comment]
Hello,

Thank you for submitting this PR! I've did a quick glance on it (looks good), however I'd like to double check it when I have the time.

**Comment by szokodiakos** [comment]
I had to commit a hotfix, could you please update your PR? @ukoester

**Comment by ukoester** [comment]
My fork is now up to date.

**Comment by szokodiakos** [comment]
hello, sorry for the late response, the code looks good, gonna merge it

**Pull request merged**
